# Generated by Django 4.2.6 on 2023-10-14 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_tasks_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='effort',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
