# Generated by Django 4.2.6 on 2023-10-17 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_tasks_context'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(choices=[('A', 'Critical'), ('B', 'Important'), ('C', 'Secondary'), ('D', 'Not Important')], max_length=1)),
                ('status', models.CharField(choices=[('Co', 'Completed'), ('Cn', 'Cancelled'), ('De', 'Delegated'), ('Ip', 'In Process'), ('Ns', 'Not Started'), ('Wa', 'Wait for')], max_length=2)),
                ('complete', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=200)),
                ('deadline', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='tasks',
            name='new_task',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='priority',
            field=models.CharField(choices=[('A', 'Critical'), ('B', 'Important'), ('C', 'Secondary'), ('D', 'Not Important')], max_length=1),
        ),
        migrations.AddField(
            model_name='tasks',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.projects'),
        ),
    ]
