# Generated by Django 4.2.6 on 2023-10-23 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_tasks_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='status',
            field=models.CharField(choices=[('Co', 'Completed'), ('Cn', 'Cancelled'), ('De', 'Delegated'), ('Ip', 'In Process'), ('Ns', 'Not Started'), ('Wa', 'Wait for')], default='Ns', max_length=2),
        ),
    ]
