# Generated by Django 4.2.6 on 2023-10-25 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_alter_projects_priority'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='name',
            new_name='project_name',
        ),
    ]
