# Generated by Django 4.2.6 on 2023-10-26 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_rename_name_projects_project_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='complete',
            new_name='project_complete',
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='deadline',
            new_name='project_deadline',
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='priority',
            new_name='project_priority',
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='status',
            new_name='project_status',
        ),
    ]
