# Generated by Django 4.2.6 on 2023-11-13 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_alter_tasks_effort'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='compound_priority',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
