# Generated by Django 4.2.6 on 2023-11-23 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_assignee_user_context_user_projects_user_tasks_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='context',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
