# Generated by Django 4.2.6 on 2023-11-25 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0017_context_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignee',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
