# Generated by Django 4.2.6 on 2024-01-26 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0018_assignee_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='project_status',
            field=models.CharField(choices=[('', 'No Status'), ('Co', 'Completed'), ('Cn', 'Cancelled'), ('De', 'Delegated'), ('Ip', 'In Process'), ('Ns', 'Not Started'), ('Wa', 'Wait for')], max_length=2),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='status',
            field=models.CharField(choices=[('', 'No Status'), ('Co', 'Completed'), ('Cn', 'Cancelled'), ('De', 'Delegated'), ('Ip', 'In Process'), ('Ns', 'Not Started'), ('Wa', 'Wait for')], default='Ns', max_length=2),
        ),
    ]
