# Generated by Django 4.2.6 on 2024-03-05 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0021_usertoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
