# Generated by Django 4.2.6 on 2024-03-05 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0022_calendar_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='last_sync',
            field=models.DateTimeField(null=True),
        ),
    ]
