# Generated by Django 4.2.6 on 2024-03-07 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0025_calendar_recurrence_rule'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertoken',
            name='last_gCal_sync',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
